namespace ReTween
{
    public enum EaseType
    {
        Linear = 0,
        QuadIn = 1,
        QuadOut = 2,
        QuadInOut = 3,
        CubicIn = 4,
        CubicOut = 5,
        CubicInOut = 6,
        QuartIn = 7,
        QuartOut = 8,
        QuartInOut = 9,
        QuintIn = 10,
        QuintOut = 11,
        QuintInOut = 12,
        BounceIn = 13,
        BounceOut = 14,
        BounceInOut = 15,
        ElasticIn = 16,
        ElasticOut = 17,
        ElasticInOut = 18,
        SlowElasticIn = 19,
        CircularIn = 20,
        CircularOut = 21,
        CircularInOut = 22,
        SinusIn = 23,
        SinusOut = 24,
        SinusInOut = 25,
        ExponentialIn = 26,
        ExponentialOut = 27,
        ExponentialInOut = 28,
        BackwardIn = 29,
        BackwardOut = 30,
        BackwardInOut = 31,
        BackwardInOutHalf = 32,
        Custom = 100,
    }
}