name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Push UPM Subtree
        run: |
          git subtree push --prefix Assets/ReTween origin upm
  
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3

#     - name: configure
#       run: ./configure

#     - name: Install dependencies
#       run: make

#     - name: Run check
#       run: make check

#     - name: Run distcheck
#       run: make distcheck
